version: "3.7"

services:
  managedhost-app-1:
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "3000:3000"
      - "2223:2223"
    environment:
      SSH_ENABLE_ROOT: "true"
    volumes:
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys

  managedhost-app-2:
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "3001:3000"
      - "2224:2224"
    environment:
      SSH_ENABLE_ROOT: "true"
    volumes:
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys

  managedhost-app-3:
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "3002:3000"
      - "2225:2225"
    environment:
      SSH_ENABLE_ROOT: "true"
    volumes:
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys

  loadbalancer:
    build:
      context: managed-host/alpine/loadbalancer
    network_mode: "bridge"
    environment:
      SSH_ENABLE_ROOT: "true"
    volumes:
      - ./managed-host/alpine/loadbalancer/nginx-config/nginx.conf:/nginx-config/nginx.conf
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys
    ports:
      - "22:22"